name: Java CI     #Actions名称

on: [push]        #Action触发条件

jobs:
  build:
    runs-on: ubuntu-latest    #运行环境
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew jar
      - name: SSH and SCP Setup
        uses: alinz/ssh-scp-action@master
        with:
          # ssh remote host
          host: ${{ secrets.IP}}
          # ssh remote port
          port: ${{ secrets.PORT}}
          # ssh user
          user:  ${{ secrets.USER}}
          # content of ssh private key. ex raw content of ~/.ssh/id_rsa
          key: ${{ secrets.PRIVATE_KEY}}
          # execute commands before SCP
          ssh_before: |
            rm -rf /root/donghang/donghang-1.0-SNAPSHOT.jar
          # scp local and remote
          scp: |
            ./build/libs/donghang-1.0-SNAPSHOT.jar ~/donghang/donghang-1.0-SNAPSHOT.jar
          # execute commands after SCP
          ssh_after: |
            java -jar /root/donghang/donghang-1.0-SNAPSHOT.jar
